# Use an AWS-provided base image for your runtime (e.g., Python 3.11)
FROM public.ecr.aws/lambda/python:3.11


# Copy function code and dependencies
COPY email_report/app.py ./
COPY email_report/requirements.txt ./


# Install dependencies
RUN pip install -r requirements.txt

# Set the CMD to your handler
CMD ["app.lambda_handler"]
