version = 0.1
[default.deploy.parameters]
stack_name = "resume-chatbot"
resolve_s3 = true
s3_prefix = "resume-chatbot"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["EmailReportFunction=047672427450.dkr.ecr.us-east-1.amazonaws.com/resumechatbote5a40065/emailreportfunction68f7dbf3repo"]
