AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application to converse with OpenAI agent

Resources:
  SessionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SessionTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: SessionId
          AttributeType: S
      KeySchema:
        - AttributeName: SessionId
          KeyType: HASH

  EmailReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageConfig:
        Command: [ "app.lambda_handler" ]
      Timeout: 15
      Events:
        DailyTrigger:
          Type: Schedule
          Properties:
            Schedule: cron(0 6 * * ? *)
      Policies:
        - AmazonDynamoDBFullAccess
        - Statement:
          - Effect: Allow
            Action:
              - ses:SendEmail
              - ses:SendRawEmail
            Resource: "*"
        - Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
            Resource: arn:aws:ssm:us-east-1:047672427450:parameter/FROM_EMAIL
    Metadata:
      Dockerfile: Dockerfile.report
      DockerContext: .
      DockerTag: v1